development:
  adapter: postgresql
  encoding: unicode
  database: aod_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: aod_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: aod_production
  pool: 5